version: '3.10'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - MY_DB_PASSWORD=${MY_DB_PASSWORD}
      - DEBUG=${DEBUG}
      - PAYMENT_REST_API_IMP=${PAYMENT_REST_API_IMP}
      - PAYMENT_REST_API_KEY =${PAYMENT_REST_API_KEY }
      - PAYMENT_REST_API_SECRET =${PAYMENT_REST_API_SECRET }  
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${MY_DB_PASSWORD}

volumes:
  db_data:
  static_volume:
  media_volume: 