version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MY_DB_PASSWORD=${MY_DB_PASSWORD}
      - DEBUG=${DEBUG}
    depends_on:
      - db
      
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${MY_DB_PASSWORD}

volumes:
  db_data:


