# Generated by Django 5.0.3 on 2024-04-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_myuser_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='myuser_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customer', serialize=False, to='customer.myuser'),
        ),
    ]
