# Generated by Django 5.0.3 on 2024-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_myuser_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_advertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_snsid',
            field=models.BooleanField(default=False),
        ),
    ]
