# Generated by Django 5.0.4 on 2024-06-24 18:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='seller.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id_copy', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_option', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('productimage_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='이미 등록된 이메일 주소입니다.')])),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='휴대폰 번호 형식이 올바르지 않습니다.', regex='^(01[016789]\\d{7,8})$')])),
                ('is_staff', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=50)),
                ('business_contact', models.CharField(max_length=50, null=True, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='seller_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='seller_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller'),
        ),
    ]
